### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by tactiago** [var/react-icon-checkbox#1]
Hi! I just installed the packege and written the same code you leave in the Usage section, but my react is displaying this error:

`./node_modules/react-icon-checkbox/style.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\react-icon-checkbox\IconCheckbox.js`

Can you figure this out?

**Comment by var** [comment]
@zatiro this should be resolved in 1.0.1
